# Generated by Django 3.0.4 on 2020-03-22 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0006_student_prfile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='prfile_pic',
            new_name='profile_pic',
        ),
    ]
